### ISSUE TITLE
It's not bringing my facebook ads data

### ISSUE THREAD

**Issue by gabrielads777** [Gladior-B-V/facebook-ads-connector#10]
The image creative metric is not showing in my report.
Error 'no data'

Hope you can help me solve this problem!
Thanks

**Comment by zoedufrenne** [comment]
Hi,

Thanks for letting us know. 
I see in my own dashboards that the issue also occurs. I will let the developers know and keep you updated on the progress!

**Comment by zoedufrenne** [comment]
Hi, 

We've updated the connector and fixxed the metric 'Ad Creative Image Url Image'. 
Could you check if the image is showing in your data studio report?
