### ISSUE TITLE
Limited to a list of 25

### ISSUE THREAD

**Issue by RedMarl-81** [Gladior-B-V/facebook-ads-connector#11]
The list of connection connections is only limited to 25, is there a way I can increase this?

<img width="793" alt="api" src="https://user-images.githubusercontent.com/91158242/166291276-3e526af4-8c80-4cbf-9331-9f0df8da40e8.png">

**Comment by daannijkamp** [comment]
@RedMarl-81 Sorry about that. All Facebook Accounts should now be displayed.

cc: @zoedufrenne

**Comment by RedMarl-81** [comment]
Great! Thank you very much!
