### ISSUE TITLE
Problems reading the data

### ISSUE THREAD

**Issue by pmonuth-bt** [Gladior-B-V/facebook-ads-connector#12]
Hi

I have the following problem. We have 125 sites and 84 ad accounts on Facebook and Instagram. We would like to use the insights in Google Data Studio here. But not everything is read for me. Is there a limit on your part or can't the meta? Can I support you in any way on this topic?

Warm greetings

Patrick Month

**Comment by daannijkamp** [comment]
Hi @pmonuth-bt,

I've also increased the limit for Instagram and Facebook. It should now work again.

cc: @zoedufrenne
