### ISSUE TITLE
There was an error retrieving this Add-on's configuration. 

### ISSUE THREAD

**Issue by kmfarooqi** [Gladior-B-V/facebook-ads-connector#13]
Community Connector Error
There was an error caused by the community connector. Please report the issue to the provider of this community connector if this issue persists.

Connector details
(#100) Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

![image](https://user-images.githubusercontent.com/109288835/178982342-6c92c623-08d7-4575-b185-740c592933ab.png)

**Comment by zoedufrenne** [comment]
Hi @kmfarooqi ,

Thanks for your message. 
Can you let me know when you get this error message? is it in the beginning of starting the dashboard or do you get this message while editing graphs? 

I would like to hear from you!
