### ISSUE TITLE
Adset name & ad name in same table

### ISSUE THREAD

**Issue by dbrighi** [Gladior-B-V/facebook-ads-connector#14]
Hi Staff,
I don't know if it's a bug or a desired behavior, but I cann't put in the same table Adset Name and Ad Name.

![Schermata 2022-07-26 alle 10 58 46](https://user-images.githubusercontent.com/3509579/180967592-8d79d952-8e97-4ac9-9bc5-4fd26c09dee1.png)

Put them in a table, individually they work. But not when put togheter.

In that way I cannot join in a single table:
(Analytics adset name <=> Facebook adset name) & (Analytics ad name <=> Facebook adset name)

Same for Campaign name.

Can you help me please?

**Comment by zoedufrenne** [comment]
Hi, 

Thanks for letting us know! 
This isn't desired behavior, we will put this on the product backlog and fix it. 

I keep you posted.
Zoé du Frenne

**Comment by dbrighi** [comment]
Thank you so much... please, let me know when it will be fixed!

**Comment by zoedufrenne** [comment]
Hi @dbrighi 

We've solved the bug. You can now combine the dimensions together in one table! See screenshot:
![image](https://user-images.githubusercontent.com/84766152/184311571-5ee4609e-fef0-43ce-bd53-494bbf48a708.png)

Would you like to help us with filling in this form?  https://forms.gle/EPhEzTWJW6bW3JjbA 
We are busy with further developing the Data Hub and we would like to know what our users would like to see next in the Data Hub. 

You would really help me!
Zoé du Frenne
