### ISSUE TITLE
How to refresh access token?

### ISSUE THREAD

**Issue by dominikmecko** [Gladior-B-V/facebook-ads-connector#15]
Hi, all my data sets are disconnected due to expired access token. Could you please advise me how to refresh it so that they work again?

**Comment by zoedufrenne** [comment]
Hi @dominikmecko, that doesn't sound good!
When you go to https://datahubapp.gladior.com/ --> login --> click on + create and select the data source (Facebook ads) and then add your credential again. 

When you've connected your credential again, your license is renewed. The data source in your data studio dashboard will work as well.

**Comment by dominikmecko** [comment]
It does not work again. Same problem. I attach a screenshot.

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/49759443/182605740-b5ea78c0-4f92-4e4d-bb9b-34f74b56b804.png">

**Comment by zoedufrenne** [comment]
![image](https://user-images.githubusercontent.com/84766152/182610603-b593b415-dba5-4c40-86ce-eb7d761ee5dd.png)
Did you add the credential again? Not just select but add as a new credential, even if it is already there as a credential.

**Comment by dominikmecko** [comment]
@zoedufrenne worked well, thank you!
