### ISSUE TITLE
Question about custom events

### ISSUE THREAD

**Issue by dominikmecko** [Gladior-B-V/facebook-ads-connector#16]
Hello! 

I hope you're well. I have a question about displaying custom events in a timeline graph. We have several custom events set up in Pixel but I cannot find a way how to show events from the Pixel and filter it according to the type. Is that possible? 

All the best
Dominik Mecko

**Comment by zoedufrenne** [comment]
Hi Dominik,

Thanks for your message. 
Unfortunately we don't have custom pixel events in the connector. These custom pixel events are per customer different and that makes the fields dynamic and hard to add to the connector.

If you would like these fields in the connector, we could make a custom connector especially for you. This will be a paid connector. If you would like this, We can plan a meeting to discuss the wishes & possibilities.
