### ISSUE TITLE
No Page Engagement Data on Some Facebook Business Page

### ISSUE THREAD

**Issue by eresfavolosx** [Gladior-B-V/facebook-ads-connector#17]
Greetings, 

Hope all is well and thank you for all the great work you are doing with these free connectors! I am currently having an issue with only certain Facebook Ads accounts in gathering the "Page Engagement" metric data. The result I am getting is 0 and it displays in my reports like this: 
![image](https://user-images.githubusercontent.com/6241741/188958238-58c9f7d6-d69b-4412-ba4f-7a53f231f8bb.png)

Despite this, other metrics from the same ad account do show up in the Google Data Studio report. Please let me know if you need any more information to look into the issue. 

Thank you in advance for all the help,

**Comment by zoedufrenne** [comment]
Hi,

Thanks for your message. 
I just want to check if I understand you ticket correctly;
You have some accounts where you can see page engagement and some accounts don't show this data. And now you want to know why it isn't showing the data for these specific accounts? is this correctly? 

I would like to hear from you, so I can help you!

**Comment by eresfavolosx** [comment]
Hi! Apologies for the delayed response. That is correct, some accounts show this data while others don't. I have the same permissions with all the accounts. I would like to know if there is a workaround for this issue or if it is possible to solve it.

**Comment by zoedufrenne** [comment]
Hi, 

How many like do you have on the facebook business page? There is a minimum necessary from Facebook, 
_demographic metrics, such as age, gender, and location, are only returned if there is data for 100 or more people._
 
See: https://developers.facebook.com/docs/graph-api/reference/v15.0/insights

Is this the case by the other accounts?

**Comment by eresfavolosx** [comment]
Thank you for clarifying this! However, all the Facebook pages that are facing this issue have well over 100 likes.

**Comment by zoedufrenne** [comment]
We hoped this would be the case, beacause for some there is data and for some not. I'm afraid we can't work arround it. I've made a note of to check it out with development. I can't promise we will find a solution for it, if we have I will let you know!

**Comment by eresfavolosx** [comment]
Hi! I hope you had a great weekend! Got it, thank you for looking into this and making the note. This free add-on is an amazing tool for me and all the work you and your team has put into this is greatly appreciated. 

Best wishes always,
