### ISSUE TITLE
Instagram Account wont Appear in Workspace

### ISSUE THREAD

**Issue by eresfavolosx** [Gladior-B-V/facebook-ads-connector#18]
Greetings again, 

I am having an issue with seeing an Instagram Account in the drop-down lists when I want to add it through the datahubapp.gladior.com dashboard. All of my other Instagram accounts appear and there is no difference in the access I have to it compared to the others. 

Thank you for all the help in advance,

**Comment by zoedufrenne** [comment]
Hi,

Is your Instagram account connected to a Facebook Page?

Instagram Professional accounts must be connected to a Facebook Page before their data can be accessed through the API. Once connected, any Facebook User who is able to perform Tasks on that Page can grant your app an access token, which can then be used in API requests.

This link can help you with connecting your Facebook Page to your Instagram Business Account: https://help.instagram.com/399237934150902

**Comment by eresfavolosx** [comment]
Hello! Hope all is well! The Instagram Professional Account is indeed connected to a Facebook Page. The only variable is that we did not make the connection. Please let me know if there is a workaround or if this issue can be solved. 

Thank you in advance,

**Comment by zoedufrenne** [comment]
Hi,

Unfortunately not. The API won't give us any data of account without this connection. 
https://developers.facebook.com/docs/instagram-api/overview (under 'Pages').
