### ISSUE TITLE
Facebook Ads data visualization problem (Dates without value and therefore without graphs in Looker Studio)

### ISSUE THREAD

**Issue by crisynata** [Gladior-B-V/facebook-ads-connector#21]
Updates the dates correctly, there are some days that it does not show any information. However, when I select the results table graph, the generalized data appears, which makes me conclude that it is taking them, only that when it is broken down to date or time level there are some missing data. This is not a problem of Looker Studio, but of the data source.

**Comment by zoedufrenne** [comment]
@crisynata can you share some screenshots or your dashboard with service@gladior.com? I'll check your data!

**Comment by crisynata** [comment]
Thanks @zoedufrenne. I will do that.
