### ISSUE TITLE
Assigning ad groups to Campaigns

### ISSUE THREAD

**Issue by MarketingSensei** [Gladior-B-V/facebook-ads-connector#22]
Hi. I use your connector and
I have a problem with configuring the Facebook Ads table in the Looker Studio report. I want to create a table with the name of the campaign and the names of the ad group (belonging to a given campaign), but when I put them together in the table, the ad group names are undefined, how to fix it? 
![1](https://github.com/Gladior-B-V/facebook-ads-connector/assets/146414971/acf47357-7aab-4d3a-9f13-3b715671f6ed)
![2](https://github.com/Gladior-B-V/facebook-ads-connector/assets/146414971/41b0d165-052f-4b03-a775-991c1f2fe13e)

**Comment by zoedufrenne** [comment]
Hi @MarketingSensei unfortunately is this not possible with our connector. With the API we make calls on the level of 'campaign/ adset name/ ad name'. The api cannot handle it if we call both evels directly in a table. This is something we unfortunately cannot work around. It takes always the data of the 'highest' level.

**Comment by MarketingSensei** [comment]
Ok, I understand, I have a question if there are any other similar metrics that can be combined to make this work

**Comment by zoedufrenne** [comment]
@MarketingSensei not to get both levels in one tabel, maybe you can try to combine the data in Looker with multiple sources?
