### ISSUE TITLE
Re-authenticate

### ISSUE THREAD

**Issue by VisibleComunicacion** [Gladior-B-V/facebook-ads-connector#23]
Good morning

Facebook Insights indicates that Re-authenticate, I do it (everything comes out correct) but the error persists. How do I request it? thank you.

**Comment by zoedufrenne** [comment]
Hi @VisibleComunicacion we've made an update with the connector! Can you revoke acces of the connector and connect a new credential in the data hub https://datahubapp.gladior.com/? Please let me know if it worked!
