### ISSUE TITLE
Facebook Ads Data Timeout

### ISSUE THREAD

**Issue by ChrisSetup** [Gladior-B-V/facebook-ads-connector#25]
Hello using your platform and the Facebook Ads connector.

When i try to extract data using the adset name or advert name variables in Google Data Studio i'm continually running into timeout errors.

![image](https://github.com/Gladior-B-V/facebook-ads-connector/assets/156669443/9e812d26-ffe7-445f-a95c-6263637b9c60)

**Comment by zoedufrenne** [comment]
Hi @ChrisSetup 

We've updated to a new version of the Facebook API. but with this switch some accounts can't get reconnected.
We are aware of this and busy with creating a solution.

I'll keep you updated when the fix is live.

**Comment by zoedufrenne** [comment]
Hi @ChrisSetup , we've made an update with the connector! Can you revoke acces of the connector and connect a new credential in the data hub https://datahubapp.gladior.com? Please let me know if it worked!

**Comment by ChrisSetup** [comment]
Hi Zoe,

I've just attempted to do that and run into an error on the data studio
side here:-

Its showing this

[image: image.png]

and when i click it i'm getting this message.  I've retried a few times and
tried changing credentials etc but still running into this error.

[image: image.png]

Any help would be appreciated

Thanks

Chris

**Comment by zoedufrenne** [comment]
Hi @ChrisSetup I can't see the screenshot. Can you send it again? 
We don't get the error anymore so I can't recreate the issue.
