### ISSUE TITLE
Facebook Ads - Community Connector Error

### ISSUE THREAD

**Issue by luca9154** [Gladior-B-V/facebook-ads-connector#26]
Hello, 
I've been using this connector since October, and everything was really good, but 2 days ago stopped working. 

As you can see from the screenshot below, it gaves me "unknown error" and there is no way to connect the data source again.

<img width="200" alt="image" src="https://github.com/Gladior-B-V/facebook-ads-connector/assets/39029984/8a725e25-54f0-4f92-af4e-09fc5dd5ee59">

Can you pls help?
Thanks for your work!

Luca

**Comment by zoedufrenne** [comment]
Hi @luca9154 ,

We've updated to a new version of the Facebook API. but with this switch some accounts can't get reconnected.
We are aware of this and busy with creating a solution.

I'll keep you updated when the fix is live.

**Comment by luca9154** [comment]
Hi @zoedufrenne,

ok thank you for the transparency.

Waiting for your updates!

**Comment by zoedufrenne** [comment]
Hi @luca9154 the Facebook Ads connector has access!
Can you check if your accounts show in the connector? :)

**Comment by luca9154** [comment]
Hi @zoedufrenne, unfortunately I get the same error as before. 

<img width="220" alt="errore_gladior" src="https://github.com/Gladior-B-V/facebook-ads-connector/assets/39029984/f87a272c-837f-4059-8c1e-7c9054e0b996">

Thanks
Luca

**Comment by zoedufrenne** [comment]
@luca9154 Can you revoke acces of the connector and add a new credential to the https://datahubapp.gladior.com (even if the credential is already there).

**Comment by luca9154** [comment]
HI @zoedufrenne, it works now!! 

Thanks for the support and for solving the issue in a short time. 

Strongly recommended!

Luca

**Comment by zoedufrenne** [comment]
That's nice to hear. Thanks Luca!
