### ISSUE TITLE
bad request 400

### ISSUE THREAD

**Issue by Moniquedbo** [Gladior-B-V/facebook-ads-connector#27]
Every time I try to connect facebook in lookerstudio via datahub I get the following message.
I have also deleted all the cookies and tried again, but I keep getting the message

![Schermafbeelding 2024-02-02 163245](https://github.com/Gladior-B-V/facebook-ads-connector/assets/158594709/c432c3e5-84a1-47b0-8183-ee71a46cafb3)

**Comment by zoedufrenne** [comment]
Hi @Moniquedbo, Could you revoke the access of the connector in Looker Studio and create a new credential in Data Hub. Even if you had allready connected the credential, you can connect it in the https://datahubapp.gladior.com.

**Comment by Moniquedbo** [comment]
Hi Zoe,

Thank you, it worked.

Met vriendelijke groet,
Monique de Boer

T. 0628096152
E. ***@***.***
<https://www.linkedin.com/in/monique-de-boer/>



Op ma 5 feb 2024 om 08:20 schreef zoegerritsen ***@***.***>:

**Comment by zoedufrenne** [comment]
@Moniquedbo Top! Goed om te horen, dankjewel!
