### ISSUE TITLE
Error connecting with the service

### ISSUE THREAD

**Issue by marcfs-analytics** [Gladior-B-V/facebook-ads-connector#28]
Hi,

first of all - thank you for the great connectors! I love it!

Since last week I don’t see any Facebook Ads data in my Looker Studio Dashboard. The error message in Looker Studio:

„Unknown Error - There was an error communicating with the service."

So I deleted the connection. But when I want to connect Facebook Ads again, this error (see screenshot) appears.

Could you please help me?

Best
Marc
<img width="881" alt="Bildschirmfoto 2024-02-08 um 12 00 24" src="https://github.com/Gladior-B-V/facebook-ads-connector/assets/390301/4c3ddc41-a922-40f1-b142-8af88cf032be">

**Comment by zoedufrenne** [comment]
Hi @MistX , 

Thanks for your message. There has been an update to the facebook ads api. At our ends it is working properly, but could you connect the credential again (even if it's already there?). and let me know if it works.

**Comment by marcfs-analytics** [comment]
Hi @zoedufrenne,

great, that helped. Thank you!

**Comment by zoedufrenne** [comment]
That's great thanks for letting me know! The support is free, but if you want you can donate us by the pink donate button in the Data Hub App (https://datahubapp.gladior.com/)
