### ISSUE TITLE
Can the metric Purchase Conversion Value be added

### ISSUE THREAD

**Issue by DanielWAY11** [Gladior-B-V/facebook-ads-connector#29]
Can the metric Purchase Conversion Value be added if possible?

**Comment by zoedufrenne** [comment]
@DanielWAY11 See our FAQ for Facebook Ads: https://datahub.gladior.com/data-sources/support-facebook-ads-connector/

The data field ‘purchase conversion value’ is not in our connector. This is because, it is a calculated field from Facebook and the Facebook API doesn’t support these fields.
