### ISSUE TITLE
The FB ads connector doesn't works

### ISSUE THREAD

**Issue by anastasiya-zholud** [Gladior-B-V/facebook-ads-connector#30]
Hello, 

Since last week I don’t see any Facebook Ads data in my Looker Studio Dashboard. The error message in Looker Studio(( 

![Screenshot_55](https://github.com/Gladior-B-V/facebook-ads-connector/assets/161433757/1739eb94-bd97-48bc-a90b-b7b5f81dd52d)
![Screenshot_54](https://github.com/Gladior-B-V/facebook-ads-connector/assets/161433757/ea9b8eb8-6f2f-4e1d-9978-358915b93767)
![Screenshot_53](https://github.com/Gladior-B-V/facebook-ads-connector/assets/161433757/abe6b6db-0374-4313-bf12-04701779b810)
![Screenshot_52](https://github.com/Gladior-B-V/facebook-ads-connector/assets/161433757/67c62ebc-784a-47de-97b6-87ca8fe0fdee)
![Screenshot_51](https://github.com/Gladior-B-V/facebook-ads-connector/assets/161433757/b5b23e81-23fc-4b12-a81c-a32785dd5957)

I have a problem using the Facebook Ads connector to Looker studio although everything worked fine before. It produces various errors and I don't understand why.

Could you please help me?

**Comment by zoedufrenne** [comment]
Hi @anastasiya-zholud , Could you connect a new credential to the [datahub](https://datahubapp.gladior.com/)? Even if the credential is already there. We've had an update from Meta for the API and had to make some adjustments to the connector. 

Please let me know if it worked!

**Comment by Jsusglz** [comment]
Hi, I have the same problem.

I have tried to reconnect my Facebook ADS account, I have tried to create a new report but nothing works. Any solution?
![Captura de Pantalla 2024-04-24 a la(s) 9 41 22](https://github.com/Gladior-B-V/facebook-ads-connector/assets/168007250/d94ff140-5c5a-4aef-96a5-b414254b075c)

**Comment by eresfavolosx** [comment]
I can confirm this issue is also happening to me. I hope there can be a resolution to this soon. @zoedufrenne

**Comment by eresfavolosx** [comment]
I wanted to inform y'all that by removing my credentials from the Data Hub console, removing the data source from Looker, and adding the data source again in Looker I was able to fix the error, at least for now. Please let me know if this works for all of you.
