### ISSUE TITLE
Facebook Ads - Revenue 

### ISSUE THREAD

**Issue by sobeski-local** [Gladior-B-V/facebook-ads-connector#31]
i cant find a metric that will show the revenue - can anyone help? it is ticket sales rather than ecom

**Comment by sobeski-local** [comment]
![image](https://github.com/Gladior-B-V/facebook-ads-connector/assets/163528957/1fdf41d1-9ae8-42da-9e5f-0b2bee63eb37)

**Comment by zoedufrenne** [comment]
hi @sobeski-local , 

See our support page: https://datahub.gladior.com/data-sources/support-facebook-ads-connector/ 
It's a calculated field, so that's why it isn't in the connector.

**Comment by sobeski-local** [comment]
sorry, dont quite understand when you say a calculated field? why are we able to get conversion numbers and roas but not the conversion value? is there any work around for this?

**Comment by zoedufrenne** [comment]
Hi @sobeski-local  All conversion values are calculated fields in Facebook (and therefore a custom fields), these are for a lot of customers different and that's why the Facebook API doesn’t support these fields so that's why we can't get it in the connector.
