### ISSUE TITLE
Community connector error

### ISSUE THREAD

**Issue by seotrackerman** [Gladior-B-V/facebook-ads-connector#34]
hi there, receiving a community connector error on all our reports we have setup with your FB ads connector

![image](https://github.com/Gladior-B-V/facebook-ads-connector/assets/171210577/360f7082-1274-4da8-b303-a3c590d9686b)

**Comment by rkooiker** [comment]
Hi @seotrackerman, Can you try to connect your credential again to the datahubapp.gladior.com (even if it's already there). Just add your credentials as a new credential.

Please let me know if it worked!

**Comment by seotrackerman** [comment]
Thanks @rkooiker , that worked :)
