### ISSUE TITLE
The value of purchases and cost per conversion are not displayed

### ISSUE THREAD

**Issue by Tom8999** [Gladior-B-V/facebook-ads-connector#35]
Purchase value/transaction value and cost per conversion metrics are not working, don't know why?
![image](https://github.com/Gladior-B-V/facebook-ads-connector/assets/171667643/f2baf6ab-4ab4-4888-9eb4-2bee4ec50cc2)

**Comment by rkooiker** [comment]
Hi @Tom8999, can you verify that this data is available in Facebook? If not, that could mean your setup is incorrect.

**Comment by Tom8999** [comment]
![image](https://github.com/Gladior-B-V/facebook-ads-connector/assets/171667643/325a5aab-589c-4dbd-baa0-bc56cda9a3c2)
Hi, I am sending a screenshot from facebook ads

**Comment by rkooiker** [comment]
It might have to do with the following:

> Facebook will no longer be able to aggregate non-inline conversion metric values across iOS 14.5 and non-iOS 14.5 campaigns due to differences in attribution logic. Querying across iOS 14.5 and non-iOS 14.5 campaigns will result in no data getting returned for non-inline conversion metrics such as app installs and purchases. Inline event metrics like impressions, link clicks, and video views, however, can still be aggregated. Please visit our [changelog](https://developers.facebook.com/docs/graph-api/changelog/non-versioned-changes/jan-19-2021) for more information.

We are looking further into the issue, are your campaings cross platform?

**Comment by Tom8999** [comment]
Yes

**Comment by rkooiker** [comment]
In that case there is nothing we can do, because of the before mentioned update by facebook.
