### ISSUE TITLE
Unknown Error - There was an error communicating with the service.  Error ID: 88a26a7d

### ISSUE THREAD

**Issue by MikeHerbs** [Gladior-B-V/facebook-ads-connector#36]
I am experiencing an error with the connector this is the 2nd time this has happened. this is for looker studio by the way

Unknown Error - There was an error communicating with the service. Error ID: 88a26a7d

I dont know why the screenshots arent uploading.

**Comment by rkooiker** [comment]
Hi, 

have you tried reconnecting your credential? If that does not work, please provide a bit more details about what you are trying to do.

**Comment by MikeHerbs** [comment]
> Hi,
> 
> have you tried reconnecting your credential? If that does not work, please provide a bit more details about what you are trying to do.

Yes i have and it still is an error in looker studio but maybe it just needs time to reestablish the connection?

**Comment by MikeHerbs** [comment]
the credentials that i have now on data hub is not showing on lookerstudio...

**Comment by MikeHerbs** [comment]
now lookerstudio says when i am trying to reconnect the the data source:

 No connection changes were found
Continue to the list of fields.

**Comment by MikeHerbs** [comment]
ok, i think it just needed time to resync everything now the data is showing once again!
