### ISSUE TITLE
Issue with Standard Event data pulling through 

### ISSUE THREAD

**Issue by jamie-weareyatter** [Gladior-B-V/facebook-ads-connector#37]
I have a query about a few of the metrics that are available within the FB data connector for Data Studio, that don't seem to be working.

The main two are for standard events like 'Add To Cart' and 'Contact'. These don't seem to be pulling through any data to our dashboards, however things like Lead or RegistrationComplete work just fine. Do you have any tips or insight?

**Comment by jamie-weareyatter** [comment]
Wondering if someone can please help with this?

**Comment by rkooiker** [comment]
Hi @jamie-weareyatter, could you share some screenshots of the data in looker and the data in the facebook ads manager? And could you also share your Data Hub user id (found under your profile > edit profile)? This would help us look further into the issue.
