### ISSUE TITLE
Facebook ads connector error

### ISSUE THREAD

**Issue by kinjaldfp** [Gladior-B-V/facebook-ads-connector#38]
Hi,
We are using your Facebook ads connector for Looker studio. It was working fine but since yesterday it is giving below error. Is there something wrong at your end? I would appreciate it if someone can please check. 

Community Connector Error
There was an error caused by the community connector. Please report the issue to the provider of this community connector if this issue persists.

Connector details
Unknown Error – There was an error communicating with the service.
![Error](https://github.com/user-attachments/assets/41aa383b-0d63-420c-80a8-6ed575308cfa)

Thanks
Kinjal

**Comment by rkooiker** [comment]
Hi @kinjaldfp,

Could you try to reconnect your credential? Please let us know if that solves it.

Kind regards,

Rob

**Comment by kinjaldfp** [comment]
Hi Rob,

Thank you for your reply. The issue got solved a few days ago.

Thanks
Kinjal
