### ISSUE TITLE
Standard event value error

### ISSUE THREAD

**Issue by magniandtudeacc** [Gladior-B-V/facebook-ads-connector#39]
Hi, 

I have a question about the following events. The event with the respective value is missing for all events. 

Missing in general:
Add to cart value
Website purchase value

The value 0 is displayed, even though there is one:
Website Customise Products

<img width="220" alt="Bildschirmfoto 2024-08-01 um 14 33 18" src="https://github.com/user-attachments/assets/1d4bdeea-0597-4215-ac96-101453f4ce77">
<img width="217" alt="Bildschirmfoto 2024-08-01 um 14 33 30" src="https://github.com/user-attachments/assets/6fa4ce91-a3b3-4cce-9c79-f3ddea0bd7e2">
<img width="217" alt="Bildschirmfoto 2024-08-01 um 14 33 46" src="https://github.com/user-attachments/assets/b48c41be-647e-4052-a2e9-b5e24c044f2f">

Thanks for help!

**Comment by rkooiker** [comment]
Hi @magniandtudeacc,

could you provide some screenshots of tthe data in facebook ads and the data on your dashboard? Also please share your Data Hub user id so that we can look further into the issue.

**Comment by magniandtudeacc** [comment]
Hi @rkooiker,

sure. See attached. I think, this ist the id: 50d88aa2
<img width="796" alt="Bildschirmfoto 2024-08-12 um 09 53 51" src="https://github.com/user-attachments/assets/e26a929b-b0dd-41d8-ae20-7d1b6fa5305e">
<img width="923" alt="Bildschirmfoto 2024-08-12 um 09 51 58" src="https://github.com/user-attachments/assets/0f82e9a1-159b-4e3c-b082-a7463ffe98ba">

**Comment by rkooiker** [comment]
Hi @magniandtudeacc, 

The fields you mentioned were indeed not working as expected. We have identified the problem, and make sure these will be fixed soon.

**Comment by rkooiker** [comment]
@magniandtudeacc The fix is now live. If you run into other fields that do not work as expected please let us know.
