### ISSUE TITLE
The Facebook Ads API version used in Looker is deprecated

### ISSUE THREAD

**Issue by alvarorhambuntious** [Gladior-B-V/facebook-ads-connector#40]
Please see attached the error from Looker. I already tried refreshing my credentials in the datahub. 

![image](https://github.com/user-attachments/assets/084450c9-35ae-4680-ad67-ccf6d44a9541)

**Comment by muhlayna** [comment]
I am also seeing this error on my looker studio. I have tried refreshing the connection and removing it and making a new one. I have also tried connecting different fields. Nothing working. 
<img width="954" alt="Screenshot 2024-08-13 at 5 08 15 PM" src="https://github.com/user-attachments/assets/d86eb0af-d9bf-475d-9edd-2b41ab1f6c5e">

**Comment by rkooiker** [comment]
This issue has been resolved.

**Comment by muhlayna** [comment]
Thank you!
