### ISSUE TITLE
connect doesn't work

### ISSUE THREAD

**Issue by dominikmecko** [Gladior-B-V/facebook-ads-connector#7]
Error message: 

There was an error caused by the community connector. Please report the issue to the provider of this community connector if this issue persists.

Connector details
There was an error caused by this connector.

Error ID: b5c5b280

**Comment by zoedufrenne** [comment]
Hi,
Thanks for sharing!

We've made an update to the connector.
When you make a new connection to the facebook ads connector, it will work properly.
