### ISSUE TITLE
Ad data not moving through

### ISSUE THREAD

**Issue by Job-Bamboo** [Gladior-B-V/facebook-ads-connector#9]
Good day I've connected and authorized the data connector however the data from Facebook is not pulling through as no data is reflecting on my score card.

Please assist with this issues.

**Comment by zoedufrenne** [comment]
Hi,

Can you tell us which metrics you are using for the score cards in the dashboard?
We've made some adjustments to the connector. Could you check if the data is showing in your dashboard or if it is still an issue?
